### ISSUE TITLE
Error Message after Authorization: Failed setup, will retry: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by nilsmau** [Phil-Barker/hass-bosch-ebike#4]
In the Integration panel, my bike & Bosch system are recognized properly, yet the integration shows: 
`Failed setup, will retry: 'NoneType' object has no attribute 'get'`

In the system logs:
it apparently fails at  `"alarm_enabled": connected_module.get("isAlarmFeatureEnabled")`

This error originated from a custom integration.

Logger: custom_components.bosch_ebike.coordinator
Source: helpers/update_coordinator.py:392
integration: Bosch eBike Flow (documentation, issues)
First occurred: 1:13:26 PM (7 occurrences)
Last logged: 1:17:24 PM

```
Unexpected error fetching bosch_ebike_********-****-****-****-************ data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 392, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch_ebike/coordinator.py", line 57, in _async_update_data
    combined_data = self._combine_bike_data(profile_data, soc_data)
  File "/config/custom_components/bosch_ebike/coordinator.py", line 111, in _combine_bike_data
    "alarm_enabled": connected_module.get("isAlarmFeatureEnabled"),
                     ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by misko85** [comment]
Updated today to 1.0.4 but it is showing still 1.0.1

**Comment by Phil-Barker** [comment]
Investigating. I have Flow+ so haven't been able to test it without - it's likely some of the parameters don't come back

**Comment by Phil-Barker** [comment]
I have pushed a fix in for this - but unable to test it as I have a Flow+ subscription

You should see v1.0.5 now - if someone can let me know if it works or not then I can close this off

With regards to updating to v1.0.4 and it still showing as v1.0.1 - that was my fault, I forgot to update the package version in the code. My apologies. This should also now be fixed

**Comment by misko85** [comment]
It works now after the update to 1.0.5.
Thank you @Phil-Barker 

![Image](https://github.com/user-attachments/assets/3aac04b6-620f-4ff2-b635-395b9a0d39a0)

![Image](https://github.com/user-attachments/assets/a47e900b-4ac1-42f3-b3d8-036c0678c843)

**Comment by nilsmau** [comment]
So far, I can confirm what @misko85 said, it seems to be working.
Thanks @Phil-Barker!
